version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VUE_APP_API_BASE_URL=http://backend:3000
      - SUBDOMAIN=Bobi
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
